config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root 'welcome#index'

  get '/blog'        => 'blog#index', as: :blog
  get '/tags'        => 'blog#tags', as: :tags
  get '/contact_form' => 'blog#contact_form', as: :contact_form
  post '/contact' =>   'blog#contact', as: :contact

  get '/what'      => 'welcome#what',  as: :what
  get '/steps'      => 'welcome#steps',  as: :steps
  get '/how_to'      => 'welcome#how_to', as: :how_to

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index

  end

  def contact
    ContactMailer.contact(params[:contact]).deliver
    redirect_to blog_path
  end

  def contact_form
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to entries_path, notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to entries_url, notice: 'Entry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entry_params
      params.require(:entry).permit(:title, :content, :tags)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def how_to
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blog/contact_form.html.slim
.container.contact
  .row
    .box
      h3 Contact Form
      = simple_form_for :contact, url: contact_path do |f|
        = f.input :name, input_html: {class: "u-full-width"}
        = f.input :email, input_html: {class: "u-full-width"}
        = f.input :message, input_html: {class: "u-full-width"}
        
        button.button-primary.u-full-width Contact me!

app/views/blog/index.html.slim
.blog
  .main
    header        
      = image_tag "bnb.jpeg"

    .header-cover
      = link_to contact_form_path do
        span airbnb
      i.fa.fa-bars

    .container
      .item
        = image_tag "item-1.jpeg"
        .caption
          h3= "The Swimmer"
      .item
        = image_tag "item-2.jpeg"
        .caption
          h3= "The Plant"
      .item
        = image_tag "item-3.jpeg"
        .caption
          h3= "That Night"
      .item
        = image_tag "item-4.jpeg"
        .caption
          h3= "The Meal"

      .item
        = image_tag "item-5.jpeg"
        .caption
          h3= "That Look"

      .item
        = image_tag "item-6.jpeg"
        .caption
          h3= "This Feel"


    .social
      p 
        b 1.4k
        | Shares
      i.fa.fa-facebook
        p 442
      i.fa.fa-twitter
        p 395
      i.fa.fa-linkedin
        p 94
      i.fa.fa-google-plus
        p 94
      i.fa.fa-envelope


    footer
      p
        i.fa.fa-copyright
        | Made with 
        i.fa.fa-heart 
        |  by Sherwyn

  .side
    i.fa.fa-close
    h5.search
      i.fa.fa-search
      | SEARCH

    h5 NEWS
    h5 WANDERLUST
    h5 HOSPITALITY
    h5 LOCAL LENS
    h5 EVENTS
    h5 STORIES
    h5 LANGUAGES

app/views/blog/tags.html.slim
.tags
  header
    .container
      = "<header> HTML </header>"

  .container
    .row
      .six.columns
        h1= "<h1> </h1>"
        h2= "<h2>  </h2>"
        h3= "<h3>  </h3>"
        h4= "<h4>  </h4>"
        h5= "<h5>  </h5>"
        p= "<p> </p>"
        input type="text" placeholder="<input>"
        br
        button= "<button> </button>"

      .six.columns
        h3
          div= "<div> </div>"
          section= "<section> </section>"
          span= "<span> </span>"

        img src="http://placehold.it/350x150?text=<img+src=''/>"

        h4
          u= "<u> Underline </u>"
          br
          b= "<b> Bold </b>"
          br
          i= "<i> Italics </i>"
          
        = link_to blog_path do
          i.fa.fa-arrow-right.fa-2x
    br

  footer 
    .container= "<footer> </footer>"

app/views/entries/_form.html.slim
= simple_form_for(@entry) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, input_html: {class: "u-full-width"}
    = f.input :content, input_html: {class: "u-full-width"}
    = f.input :tags, input_html: {class: "u-full-width"}

  .form-actions
    = f.button :submit

app/views/entries/edit.html.slim
.container
  h1 Editing entry

  == render 'form'

  = link_to 'Show', @entry
  '|
  = link_to 'Back', entries_path

app/views/entries/index.html.slim
.container.entries
  h1 
    | My Diary
    = link_to new_entry_path do
      i.fa.fa-plus
  
  -@entries.each do |entry|
    section
      = link_to entry, data: {:confirm => 'Are you sure?'}, :method => :delete do
        i.fa.fa-close
      h4
        = "#{entry.title} - "
        small
          = link_to edit_entry_path(entry) do
            i.fa.fa-pencil
      h5
        small = "#{entry.tags}"
      p #{entry.content}
      p.created-at
        i= "#{entry.created_at.strftime('%A, %b %d')}"

app/views/entries/new.html.slim
.container.new-entry
  h1 New entry

  == render 'form'

  = link_to  entries_path do
    i.fa.fa-arrow-left.fa-2x

app/views/entries/show.html.slim
p#notice = notice

p
  strong Title:
  = @entry.title
p
  strong Content:
  = @entry.content
p
  strong Tags:
  = @entry.tags

= link_to 'Edit', edit_entry_path(@entry)
'|
= link_to 'Back', entries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsGirls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.slim
.container.welcome.index
  .row
    .twelve.columns
      h1 Hello!
      h4 
        | You are here to learn Ruby on Rails to build 
        u Web Applications.
        br
        | Who uses Ruby on Rails?
        br
        br
        = link_to "Groupon", "http://www.groupon.sg/"
        | , 
        = link_to "Airbnb", "https://www.airbnb.com.sg/"
        | , 
        = link_to "Hulu", "https://www.airbnb.com.sg/"
        br

      h3= link_to "Setup on Nitrous/Locally? Let's start", what_path

app/views/welcome/steps.html.slim
.container.welcome.steps
  .row
    .twelve.columns
      h2
        | Steps
      h4
        ol
          li
            a.to-show
              | Create a project
            .hidden
              | Type in terminal: 
              u rails new project_one && cd project_one && rails server
          li 
            a.to-show
              | Receive a request 
            .hidden 
              | Type in 
              u config/routes.rb
              .type 
                | get 
                span.lightblue "/" 
                | => 
                span.lightblue "welcome#index"
              
          li 
            a.to-show
              | Direct a request

            .hidden 
              | Type in terminal: 
              u touch app/controllers/welcome_controller.rb
              br
              | Type in 
              span.file app/controllers/welcome_controller.rb
              .type 
                span.red def 
                | index
                .indent
                span.red end


          li 
            a.to-show Display a page 
            .hidden 
              | Type in terminal: 
              u touch app/views/welcome/index.html
              br
              | Type in 
              span.file app/views/welcome/index.html
              .type 
                span.red= "<h1>"
                |  Hello! 
                span.red= "</h1>"

          li 
            | Go to your browser 
            small= "(http://localhost:3000)"

      h3= link_to "What next?", tags_path

app/views/welcome/what.html.slim
.container.welcome
  .row
    .twelve.columns
      h1 What are you making today?
      h3 - Three Webpages (Or more!)
      h5= link_to "These are the steps", steps_path